name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Check out the repository code
    - name: Check out repository
      uses: actions/checkout@v2

    # Set up JDK 20
    - name: Set up JDK 20
      uses: actions/setup-java@v1
      with:
        java-version: '20'

    # Cache the Maven dependencies to speed up builds
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Build and run tests with Maven
    - name: Build with Maven
      run: mvn -B install --file pom.xml

    # Run unit tests
    - name: Run tests
      run: mvn test
